---
# tasks file for oracle_java

#
# Note that I am following the directions I was given by Matt
# Bradcovich for installing Oracle Java 11 on Debian 9.
#
# Matt's instructions appear to be identical to those found here:
# https://tecadmin.net/install-oracle-java-11-on-debian-9-stretch/
#

- name: Get the GPG key for the Oracle Java PPA
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA8CACC073C3DB2A

- name: Add the PPA that contains Oracle Java
  apt_repository:
    repo: deb http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic main

- name: Accept the Oracle license so the installer won't prompt at install time
  debconf:
    name: oracle-java11-installer
    question: shared/accepted-oracle-license-v1-2
    value: 'true'
    vtype: select

- name: Copy over the Oracle Java archive
  copy:
    src: jdk-11.0.5_linux-x64_bin.tar.gz
    # Note that the resiling slash here means that the directory will
    # be created if it does not exist.  See here for details:
    # https://docs.ansible.com/ansible/latest/modules/copy_module.html#parameters
    dest: /var/cache/oracle-jdk11-installer-local/

- name: Install Oracle Java
  package:
    name:
      - oracle-java11-installer-local
      - oracle-java11-set-default-local
